// Home
export const HOME_HANDLE_STATE = "HOME_HANDLE_STATE";
export const HOME_TOGGLE_MODAL = "HOME_TOGGLE_MODAL";
export const HOME_UPLOAD_DOCUMENTS = "HOME_UPLOAD_DOCUMENTS";
export const HOME_SEND_DOCUMENTS = "HOME_SEND_DOCUMENTS";
export const HOME_SEND_DOCUMENTS_SUCCESS = "HOME_SEND_DOCUMENTS_SUCCESS";
